namespace nez.net.transport;

public enum TransportCode : byte
{
    // Server
    SERVER_STARTED,
    SERVER_STOPPED,
    SERVER_CLIENT_CONNECTED,
    SERVER_CLIENT_DISCONNECTED,
    SERVER_CLIENT_CONNECTION_LIMIT_REACHED,
    
    // Client
    CLIENT_CONNECTED,
    CLIENT_DISCONNECTED,
    CLIENT_ALREADY_CONNECTED,
    CLIENT_CONNECTION_TIMEOUT,
    MAXIMUM_CONNECTION_REACHED,
    CLIENT_CONNECTION_REFUSED,
    CLIENT_ERROR
}