namespace nez.net.transport;

public enum TransportCode : byte
{
    // Server
    SERVER_STARTED = 1,
    SERVER_STOPPED = 2,
    SERVER_CLIENT_CONNECTED = 3,
    SERVER_CLIENT_DISCONNECTED = 4,
    SERVER_CLIENT_CONNECTION_LIMIT_REACHED = 5,
    
    // Client
    CLIENT_CONNECTED = 100,
    CLIENT_DISCONNECTED = 101,
    CLIENT_ALREADY_CONNECTED    = 102,
    CLIENT_CONNECTION_TIMEOUT = 103,
    MAXIMUM_CONNECTION_REACHED = 104,
    CLIENT_CONNECTION_REFUSED = 105,
    CLIENT_ERROR = 106,
}